### ISSUE TITLE
Thaumcraft Text Too Big

### ISSUE THREAD

**Issue by AngelKairi** [John-Smith-Modded/JSTR-Modded-1.7.x#124] opened 2015-09-08 00:12 UTC
In the recent texture pack update, the Thaumonomicon text is just.. a little too big. The previous update had readable fonts.

![](http://i.imgur.com/WQytb2w.png)

**Comment by spannerman79** [comment] 2015-09-08 11:59
Personally I think that the font should be moved into a separate texture pack - like the 64x one.

I rather unicode (with a unicode mod i found to fix unicode text) which makes text very readable

**Comment by ArfourFoulkesayke** [comment] 2015-11-02 10:34
I support what spannerman79 said. I always remove the font for this very reason.

**Comment by Oddface** [comment] 2015-11-02 13:57
Hm, I thought we had fixed this. https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/51

**Comment by spannerman79** [comment] 2015-11-02 21:16
What many users do, (including myself) use a mod like [Unicode Font Fixer](http://minecraft.curseforge.com/projects/unicode-font-fixer) to clean up the derpy way that minecraft deals with fonts.

Personally I am quite use to Unicode font (linux user) even though language wise I have no need for unicode specific font. To me to cleaner and easier to read.  Plus many other mods (OpenComputers uses unicode font for the screen displays) are starting to code/accept unicode as a default for many users.

To be blunt I was able to remove the font ( out outlined here https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/51#issuecomment-71331495 ) but whatever was done afterwards the ability to use unicode has been screwed up.

This isn't a mod issue - remove this resource pack and there is no issue, add this resource pack and the issue is clearly visible.

**Comment by AngelKairi** [comment] 2015-11-02 22:11
But. I don't use that unicode font fixer. (And this thing is like 2 months old, prob fixed by now)

**Comment by GirmSquirrel1** [comment] 2016-05-08 14:19
So as of May 8th has there been any attempts at either having a separate resource pack for just text or just a patch for johnsmith text information?  I am a user of both thaumcraft and botania which have this same problem?  Ultimately I really enjoy this resource pack but being unable to read information doesn't help.

**Comment by Oddface** [comment] 2016-05-08 14:35
Yeah, this issue just keeps popping up. Maybe there will be a day when the Minecraft font system doesn't suck, but until then I say we should just change to a simpler font. Maybe just an upscale of the default font like in the Faithful pack.

**Comment by Oddface** [comment] 2016-05-26 09:47
Does anyone have this issue with the newest release or the alpha release we put out in march? The game needs to be restarted after applying the pack, but after that the books should be readable with the John Smith font.

**Comment by Oddface** [comment] 2016-05-28 09:35
Looks like it has been fixed. Closing this for now.

**Closed by Oddface** 2016-05-28 09:35 UTC
Labels: bug
